USER root
RUN sh -exc 'pkgs="jq" &&\
    if ( apt-get --version >/dev/null 2>&1; );then\
        pkgs="$pkgs xz-utils sudo";\
    else\
        pkgs="$pkgs xz sudo";\
    fi\
    && NONINTERACTIVE=1 WANT_UPDATE=1 cops_pkgmgr_install.sh $pkgs'
