env:
  DOCKER_BUILDKIT: "1"
  COMPOSE_DOCKER_CLI_BUILD: "1"
  BUILDKIT_PROGRESS: "plain"
  NO_SQUASH: ""
  NO_SILENT: "1"
  NONINTERACTIVE: "1"
  FORCE_ONLINE: "1"
  NBPARALLEL: "2"
  RELEASABLE_REPOS: "^corpusops/"
  RELEASABLE_BRANCHES: "^(refs/heads/)?(master|2.0|workflows)$"
  COPS_URL: "https://github.com/corpusops/corpusops.bootstrap"
  COPS_ROOT: "${{github.workspace}}/local/corpusops.bootstrap"
  silent: "$COPS_ROOT/bin/cops_shell_common output_in_error silent_vv"
  DOCKER_RELEASER: "${{ secrets.DOCKER_HUB_USERNAME }}"
  DOCKER_PASSWORD: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
jobs:
  r:
    runs-on: ubuntu-20.04
    env: {IMAGES: "${{matrix.IMAGES}}"}
    steps:
      - name: Set vars
        run: |-
            if ( echo "$GITHUB_REF" | egrep -q "${RELEASABLE_BRANCHES}" ) \
            && ( echo "$GITHUB_REPOSITORY" | egrep -q "${RELEASABLE_REPOS}" )
            then releasable=true;else releasable=false;fi
            echo "::set-output name=releasable::$releasable"
            echo "::set-output name=silent::$(echo $silent)"
        id: v
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Activate docker experimental
        run: |-
          sudo bash -exc "service docker stop;python -c \
          \"d='/etc/docker/daemon.json';\
          import json;c=json.load(open(d));c['experimental']=True;\
          open(d, 'w').write(json.dumps(c))\"
          systemctl restart docker"
      - uses: actions/checkout@v2
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache
            local
          key: 6-${{ runner.os }}-${{ github.ref }}-${{ github.repository }}-venvstatics
      - name: setup
        run: set -e;i=$(whoami);sudo sh -c "chown -Rf $i .";
             ./main.sh refresh_corpusops;
             sudo sh -c 'apt-get update -qq && apt-get install -qqy --force-yes parallel'
      - name: refresh images
        run: set -e;if (echo $IMAGES|grep -q zleftover);then
             rm -f */*/*/Dockerfile&&${{steps.v.outputs.silent}} ./refresh_images.sh;
             fi
      - name: build & release
        run: set -e;
             if [ "x${{steps.v.outputs.releasable}}" = "xtrue" ];then export DO_RELEASE=1;fi;
             ./build.sh $IMAGES
# ${{steps.v.outputs.silent}} ./build.sh $IMAGES
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        IMAGES:
        - "corpusops/opensearch/1.2.1 corpusops/opensearch/1.2.0 corpusops/opensearch/latest"
        - "corpusops/slapd/latest"
        - "corpusops/elasticsearch/7.14.2 corpusops/elasticsearch/5 corpusops/elasticsearch/2 corpusops/elasticsearch/1"
        - "corpusops/postgres/14 corpusops/postgres/13 corpusops/postgres/12"
        - "corpusops/postgres/11 corpusops/postgres/10 corpusops/postgres/9"
        - "corpusops/postgis/13-3 corpusops/postgis/13-2.5 corpusops/postgis/13"
        - "corpusops/postgis/12-3 corpusops/postgis/12-2.5 corpusops/postgis/12"
        - "corpusops/postgis/11-3 corpusops/postgis/11-2.5 corpusops/postgis/11"
        - "corpusops/postgis/10-3 corpusops/postgis/10-2.5 corpusops/postgis/10-2.4 corpusops/postgis/10 corpusops/postgis/9"
        - "corpusops/solr/slim corpusops/solr/8-slim corpusops/solr/7-slim corpusops/solr/6-slim corpusops/solr/5-slim"
        - "corpusops/solr/latest corpusops/solr/8 corpusops/solr/7 corpusops/solr/6 corpusops/solr/5"
        - "corpusops/mariadb/10 corpusops/mariadb/10-bionic corpusops/mariadb/10-focal corpusops/mariadb/10-jessie"
        - "corpusops/mariadb/5 corpusops/mariadb/5-trusty corpusops/mariadb/5-wheezy"
        - "corpusops/mariadb/bionic corpusops/mariadb/focal corpusops/mariadb/jessie corpusops/mariadb/latest"
        #- "corpusops/test/a corpusops/test/b corpusops/test/c"
        # all images that werent explicitly told to be built would be built in the next batches
        # we span them onto N jobs
        - "zleftover:1/14"
        - "zleftover:2/14"
        - "zleftover:3/14"
        - "zleftover:4/14"
        - "zleftover:5/14"
        - "zleftover:6/14"
        - "zleftover:7/14"
        - "zleftover:8/14"
        - "zleftover:9/14"
        - "zleftover:10/14"
        - "zleftover:11/14"
        - "zleftover:12/14"
        - "zleftover:13/14"
        - "zleftover:14/14"
on:
  push:
  workflow_dispatch:
  schedule: [{cron: '1 0 1,3,5,15,17,19 * *'}]
